### PR TITLE
Mac os

### PR DESCRIPTION
**Pull request by mervebduman**

### CODE REVIEW

**Comment by flying-sheep** [comment]
Hi! Was closing this PR intentional?

**Comment by mervebduman** [comment]
> Hi! Was closing this PR intentional?

Yes, sorry I mistakenly open the pull request for the theislab main branch. I was aiming for AchimKramerLab main branch.

**Comment by flying-sheep** [comment]
I see! Hm, I don’t quite see why there should be two versions of the pipeline at all. That’s just confusing and leads to people not finding the best version.

**Comment by mervebduman** [comment]
Hmm... I thought it would be clear when I drop some notes on the readme... What would you suggest? Because I can't run the original pipeline on MacOS, and I have the working version now. But it might not work on other systems, I can't test it.

**Comment by flying-sheep** [comment]
Good idea! I think updating the readme would help! Then people who care can unify the pipeline.

**Pull request closed without merging**
